<footer>
    
    <p style="font-size: 0.75vw; color: #C4C4C4; margin-top: 0.5em;">
        <a href="https://student-team-y0h6dox9.atlassian.net/jira/software/projects/SCRUM/boards/1">Jira Board</a> |
        <a href="https://github.com/103429611/Applied-Web-Project-Part-2">GitHub Repository</a> |
        <a href="mailto:info@infrawatch.com.au">info@infrawatch.com.au</a> <!-- the mailto will directly open the user's email app-->
    </p>
    <p style="font-size: 0.75vw; color: #C4C4C4; margin-top: 0.5em;">© 2025 InfraWatch. All rights reserved.</p>
</footer>