<header>
    <a href="images/logo.png"> <img src="images/logo_small.png" class="header" id="logo"  alt="InfraWatch Logo"></a> <!-- the alt is just added for acessibility-->
    <h1 class="header" id="title">InfraWatch - Jobs</h1>
    <p class="header" id="subtitle">Powering Smarter Infrastructure.</p>

    <nav class="header" id="nav"> <!--Navigation-->
        <a id="about" href="about.php">About</a>
        <a id="apply" href="apply.php">Apply</a>
        <a id="index" href="index.php">Index</a>
        <a id="jobs" href="jobs.php">Jobs</a>
    </nav>
</header>